version: "3.8"

services:
  # Rails app service
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app

  # PostgreSQL service
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myapp_user
      POSTGRES_PASSWORD: myapp_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
